name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: npm install -g snyk
      - run: snyk auth [25fb3a3d-e17e-48d7-b374-ce7cc3d3ab28]
