name: learn-github-actions
on: [push]
jobs:
  run-snyk-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: snyk/actions/maven@master
        continue-on-error: true
      - run: npm install -g snyk  
      - run: snyk auth 9e78624a-31fe-4f96-b96f-caab1830528f
      - run: snyk test
